name: test

on:
  - push

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: npm install
        run: |
          make install
      - name: Run tests
        run: |
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_TOKEN }}